name: base 
channels:
  - conda-forge
  - nvidia
  - rapidsai
dependencies:
  - cupy
  - cupy-xarray
  - cudf=25.04
  - cuspatial=25.04
  - cuproj=25.04
  - python=3.12
  - 'cuda-version>=12.0,<=12.8'
  - xarray-spatial
## Regular
  - boto3
  - cartopy
  - distributed
  - earthaccess
  - exactextract
  - fiona
  - fsspec
  - gcsfs
  - gdal
  - geoarrow-types
  - geopandas
  - geocube
  - h5netcdf
  - icechunk
  - jupytergis
  - leafmap
  - libgdal-arrow-parquet
  - localtileserver
  - mapclassify
  - maplibre
  - minio
  - netCDF4
  - odc-geo
  - odc-stac
  - planetary-computer
  - pmtiles
  - polars
  - pyarrow
  - pydeck
  - pyogrio
  - pystac
  - pystac-client
  - rasterio
  - rasterstats
  - requests
  - rio-cogeo
  - rioxarray
  - stackstac
  - streamlit
  - tippecanoe
  - tqdm
  - xarray
  - zarr
  - pip
  - pip:
    - git+https://github.com/boettiger-lab/cng-python.git
    - pcodec
