name: CUDA Spatial extension
on:
  workflow_dispatch: null
  push:
    paths: 
      - cuda-spatial
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      BASE: 'rocker-org/cuda'
    steps:
      - name: free extra disk space
        run: |
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
          df -h
      - uses: actions/checkout@v3
      - name: Publish to GitHub Container Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: rocker-org/cuda-spatial
          buildargs: BASE
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          context: cuda-spatial
      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: rocker/cuda-spatial
          buildargs: BASE          
          context: cuda-spatial
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

