name: Spatial+CUDA extension
on:
  workflow_dispatch: null
  push:
    paths: 
      - extend/Dockerfile
      - extend/environment.yml
      - extend/install.r
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      BASE: 'rocker/cuda'
    steps:
      - name: free extra disk space
        run: |
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
          df -h
      - uses: actions/checkout@v3
      - name: Publish to GitHub Container Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: rocker-org/cuda-spatial
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          buildargs: BASE
          registry: ghcr.io
          context: extend
      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: rocker/cuda-spatial
          context: extend
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          buildargs: BASE

